### ISSUE TITLE
tokens/style/global.css

### ISSUE THREAD

**Issue by zenitzo** [buka-studio/www-marijanasimag#2]
I fell in love with this website and was extremley interested in learning from it. but i can't run it on local host because i believe the glabal.css file is under the git.ignore

i would really love to learn how you accomplished certain animations on here.

thank you so much 

sincerely,
Chris

<img width="1279" alt="Screenshot 2023-08-11 at 3 28 16 PM" src="https://github.com/buka-studio/www-marijanasimag/assets/107893812/39d61b9a-39cd-4611-b3c1-bc012842e4f6">

**Comment by rpavlini** [comment]
Hi Chris,
awesome to hear you like the site!

To get things up an running you can run `npm run build-tokens` to generate the necessary CSS files.
I've also prefixed `npm run dev` with it for now.

Some things are still WIP but we'll update the readme soon to make the setup clearer.
Let me know if you run into any other issues!

**Comment by zenitzo** [comment]
awesome, thank you for taking the time to reply. Looking forward to analyzing and learning from your wonderful work 🙏🏼
